version: '3.1'
services:
  statistics-service:
    build: ./statistics/service
    image: statistics-service
    container_name: statistics-service
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/statistics
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  stats-db:
    image: postgres:14-alpine
    container_name: db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=statistics
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
