create table if not exists apps
(
    app_id bigint generated by default as identity primary key,
    name     varchar(200) not null,
     unique (name)
);

create table if not exists hits
(
    hit_id bigint generated by default as identity primary key,
    uri varchar(2000) not null,
    app_id bigint not null,
    ip varchar(50) not null,
    timestamp    timestamp not null,
    constraint fk_hits_app_id
           foreign key (app_id)
           references apps (app_id) ON DELETE CASCADE
);