create table temp_place_type
(
    type_id bigint generated by default as identity primary key,
    name varchar(100) not null CHECK (char_length(name) >= 1),
    unique (name)
);

insert into temp_place_type (name) values ('Cinema'), ('Concert hall'), ('Theatre'),
('For children'), ('Exhibition'), ('Sport'),('Stand-up'),('Quest'),('Park'),
('City'), ('Village'), ('Restaurant'), ('Cafe'), ('Hotel'), ('Beauty salon'),
('Shopping center'), ('Tourist club'), ('Yacht club'), ('Rental agency'),
('Boat station'), ('Christmas and New Year'), ('Place of interest'), ('Country club');

merge into place_type as pt
using temp_place_type tpt
on pt.name = tpt.name
when not matched then
    insert (name) values (tpt.name);

drop table temp_place_type;